Fixed and built out application page
Lambda-School-Labs/micro-fund-fe-b pull request #15
Opened 2021-01-20 20:14 UTC by Teagankeith

## Description

Refactored the application page component, facing a weird bug that makes the user click on the input box
whenever they try to enter a new character. Working on the React Query side to finish the functionality of submitting an
application.

## Trello link (and other relevant links)

[Trello card](https://trello.com/c/kWn6GMZX/14-1-as-a-partner-admin-i-can-fill-out-an-application-to-partner-with-the-main-organization)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Also

- [ ] Use small commits with clear, relevant titles and descriptions

- [ ] Scope the pull request to a single relevant feature

- [ ] Remove print statements and commented out code

- [ ] Review by two team-members before merging

2021-01-21 20:26 UTC, fatima-rizvi approved these changes
Nice job!

2021-01-21 20:44 UTC, buchananta requested changes
Everything looks great except deleting all the devDependencies.

2021-01-21 20:44 UTC, buchananta commented on package.json
> -    "yaml": "^1.10.0"
We can't delete these dependencies. They are needed for the testing.

2021-02-03 18:06 UTC, rodhent approved these changes

2021-02-03 18:51 UTC, merged